version: "3.8"
services:
  decenter.train_v2:
    environment:
      - DATA_DIR='/data'
      - OUTPUT_DIR='/outputs'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - cmd=train_v2
    volumes:
      - ./data:/data
      - ./outputs:/outputs

    healthcheck:
      test:
        [
          "CMD",
          "/app/venv/bin/python",
          "/app/main.py",
          "train_v2",
          "-t=linear-regression.ipynb",
          "-i=/app/samples/sample_v3/sample_v3.zip",
        ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
