name: Create Lilypad V2 Module

on:
  push:
    branches:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write

jobs:
  create_lilypad_v2_module:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

    - name: Create a lilypad tmpl
      run: cp lilypad_module.json lilypad_module.json.tmpl

    - name: Commit
      run: |
        git add .
        git commit -m "chore: lilypad module v2"

    - name: Push
      run: |
        git push
